name: WolfCommand
version: 2.1
description: Serious taming!
author: PuppyFirelyte
website: https://github.com/puppyize/WolfCommand

main: me.puppyize.wolfcommand.WolfCommand
database: false

commands:
  wolf:
    description: Commands to control tamed wolves
    usage: |
      /<command> sit 
      /<command> stand
      /<command> untame [number]
      /<command> color <color> [sit|stand|number]