name: WolfCommand
main: me.puppyize.wolfcommand.WolfCommand
version: 1.9

commands:
  wolf:
    description: Command to force all personally tamed wolves to sit or stand
    usage: /wolf [sit|stand]