# WolfCommand Standard Config
PLAYER_MAX_WOLF: -1
DISABLE_STICK_DAMAGE: true

# Global Command Permission
WOLF_SIT: true
WOLF_STAND: true
WOLF_UNTAME: true
WOLF_COLOR: true
WOLF_SEND: true
WOLF_HEAL: true