name: WolfCommand
version: 2.9.0
description: Serious taming!
author: Puppyize
website: https://github.com/puppyize/WolfCommand

main: me.puppyize.wolfcommand.WolfCommand
database: false

commands:
  wolf:
    description: Commands to control tamed wolves
    usage: |
      Commands:
      /<command> sit [color|number]
      /<command> stand [color|number]
      /<command> untame [color|number]
      /<command> color <color> [sit|stand|number]
      /<command> send <PlayerName> [sit|stand|number]
      /<command> heal [sit|stand|color]
      /<command> stats [PlayerName]